### ISSUE TITLE
Expand/collapse all button does not work in Safari 10.1.2

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#450]
This error appears in the console when clicking on "collapse all":

collapseAll.directive.js:16TypeError: c of elements is not a function. (In 'c of elements', 'c of elements' is undefined)

It looks like "let" is an ES6 feature no supported by all browsers.

**Comment by nhammond** [comment]
Fixed in 9b37cdb43291788f4bf60c9a9cfed707db43cf76
